### ISSUE TITLE
How to add additional information to Failure?

### ISSUE THREAD

**Issue by heckad** [dry-python/tutorials#38]
I want to add information about ValidationError exception (for example name of the missing column), but to do it I should write all possible variants of these messages. Will be adding the ability for sending additional information?

**Comment by proofit404** [comment]
Hi!

Thank you for giving the dry-python project a try!

There is a recent discussion in Gitter with code examples answering exactly the same question: https://gitter.im/dry-python/stories?at=5cefc0386f530d3b610963bf

We will include it in the docs before next release.

Feel free to ask any further questions in Gitter or reopen this issue.

Regards,
Artem.
